name: pyds9-modern
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - xpa
  - astropy>=5.0
  - numpy>=1.20
  - pytest>=7.0
  - pytest-cov
  - pip
  - setuptools>=68
  - wheel
  - sphinx
  - pip:
      - git+https://github.com/pyAstroDude/pyds9-modern.git
