[metadata]
name = pyds9
version = 1.9.dev
description = Python connection to ds9 via XPA
long_description = Python/DS9 connection via XPA (with numpy and astropy support)
author = Bill Joye and Eric Mandel
author_email = saord@cfa.harvard.edu
license = BSD
url = https://github.com/ericmandel/pyds9

[options]
packages = find:
include_package_data = True
zip_safe = False
python_requires = >=3.10
install_requires =
    astropy
    numpy

[options.packages.find]
include =
    pyds9
    pyds9.*

[options.package_data]
pyds9 =
    data/*

[options.extras_require]
test =
    pytest
    pytest-cov

[entry_points]
